### ISSUE TITLE
Unknown error with huge debug message

### ISSUE THREAD

**Issue by WittmannF** [dylantientcheu/urplus#45]
Hello, urplus stopped working today and I have no idea why. Not sure if it is related, but yesterday I was learning how how to create chrome extensions and I was checking the source code of urplus on my machine. Here's the debug message:

```
127.0.0.1 - - [28/Nov/2019 19:11:06] "GET /api/v1/remarks/submission-info/?submission_id=2042332 HTTP/1.1" 200 -
127.0.0.1 - - [28/Nov/2019 19:11:08] "GET /api/v1/remarks/all/?project_name=Finding+Donors+for+CharityML HTTP/1.1" 200 -
Internal Server Error: /api/v1/remarks/submission-critiques/
Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/OpenSSL/SSL.py", line 1538, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (54, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(54, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='review-api.udacity.com', port=443): Max retries exceeded with url: /api/v1/me.json (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/urplus/backend/urplus/middleware.py", line 18, in __call__
    headers=request.udacity_headers,
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='review-api.udacity.com', port=443): Max retries exceeded with url: /api/v1/me.json (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))
Internal Server Error: /api/v1/remarks/submission-critiques/
Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/OpenSSL/SSL.py", line 1538, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (54, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(54, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='review-api.udacity.com', port=443): Max retries exceeded with url: /api/v1/me.json (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/whitenoise/middleware.py", line 25, in __call__
    response = self.get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/urplus/backend/urplus/middleware.py", line 18, in __call__
    headers=request.udacity_headers,
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='review-api.udacity.com', port=443): Max retries exceeded with url: /api/v1/me.json (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))
Internal Server Error: /api/v1/remarks/submission-critiques/
Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/OpenSSL/SSL.py", line 1538, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (54, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(54, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='review-api.udacity.com', port=443): Max retries exceeded with url: /api/v1/me.json (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/whitenoise/middleware.py", line 25, in __call__
    response = self.get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/urplus/backend/urplus/middleware.py", line 18, in __call__
    headers=request.udacity_headers,
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='review-api.udacity.com', port=443): Max retries exceeded with url: /api/v1/me.json (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))
127.0.0.1 - - [28/Nov/2019 19:11:12] "GET /api/v1/remarks/submission-critiques/?submission_id=2042332 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/whitenoise/middleware.py", line 25, in __call__
    response = self.get_response(request)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/wittmann/urplus/backend/urplus/middleware.py", line 18, in __call__
    headers=request.udacity_headers,
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='review-api.udacity.com', port=443): Max retries exceeded with url: /api/v1/me.json (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),))
```

Any idea how to correct this? 
Thanks!

**Comment by WittmannF** [comment]
Nevermind. The elves solved this problem for me when I restarted the laptop :)

**Comment by WittmannF** [comment]
The issue is back. It is super weird. Sometimes it works and sometimes it doesn't.

**Comment by dylantientcheu** [comment]
Yes, super weird, haven't encountered it yet.
I'll try to reproduce and investigate that whenever(if ever) I get a new review. 
TBH from the logs I have no idea.

**Comment by WittmannF** [comment]
Thanks for the quick reply @blurdylan! I also found the following messages when clicking in errors:

![Screen Shot 2019-11-28 at 18 36 28](https://user-images.githubusercontent.com/5733246/69832570-e12e3c80-120d-11ea-94f5-5ce6dd5eec8c.png)

![Screen Shot 2019-11-28 at 18 35 14](https://user-images.githubusercontent.com/5733246/69832545-c065e700-120d-11ea-8608-c84f2c27f8ee.png)

![Screen Shot 2019-11-28 at 18 35 04](https://user-images.githubusercontent.com/5733246/69832547-c360d780-120d-11ea-8681-7de028eb0a53.png)
